from __future__ import annotations

import base64
import logging
import mimetypes
import re
from pathlib import Path
from urllib.parse import urlparse

import markdown as md

from ..models import Digest

log = logging.getLogger(__name__)

_MD_EXTENSIONS = ["extra", "sane_lists", "smarty"]

# Matches an entire <p>https://...</p> paragraph (a "hero link" line from the LLM).
_HERO_LINK_PARA = re.compile(
    r"<p>(https?://[^\s<]+)</p>", re.IGNORECASE
)

# Matches the "Also in today's feed" h2 and everything after it so we can
# wrap the whole runners-up section in <details>.
_RUNNERS_UP_SECTION = re.compile(
    r'(<h2[^>]*>[^<]*Also in today[^<]*</h2>)(.*)$', re.DOTALL
)

_HTML_SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<article>
{banner}
{body}
<div class="footer">Generated by contextizer · {footer_meta}</div>
</article>
</body>
</html>
"""


def render_html(digest: Digest, css: str, banner_url: str | None = None) -> str:
    """Render a digest to a self-contained HTML string."""
    date_str = digest.generated_at.strftime("%Y-%m-%d")
    title = f"Daily Digest — {date_str}"

    body_html = md.markdown(digest.rendered_markdown, extensions=_MD_EXTENSIONS)
    body_html = _promote_hero_links(body_html)
    body_html = _wrap_runners_up(body_html)
    banner_html = _render_banner(banner_url)
    footer_meta = digest.generated_at.strftime("%Y-%m-%d %H:%M UTC")

    return _HTML_SHELL.format(
        title=title,
        css=css,
        banner=banner_html,
        body=body_html,
        footer_meta=footer_meta,
    )


def load_css(css_file: Path) -> str:
    if css_file.exists():
        return css_file.read_text(encoding="utf-8")
    log.warning("CSS file missing: %s (falling back to empty)", css_file)
    return ""


class HtmlSink:
    """Write each digest as a standalone HTML file."""

    def __init__(
        self,
        out_dir: Path,
        css_file: Path,
        banner_url: str | None = None,
    ) -> None:
        self.out_dir = out_dir
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self._css = load_css(css_file)
        self.banner_url = banner_url

    def write_digest(self, digest: Digest) -> None:
        document = render_html(digest, self._css, self.banner_url)
        date_str = digest.generated_at.strftime("%Y-%m-%d")
        out = self.out_dir / f"{date_str}.html"
        out.write_text(document, encoding="utf-8")
        log.info("Wrote HTML digest to %s", out)

    def close(self) -> None:
        pass


# --- rendering helpers (module-private) ---


def _wrap_runners_up(html: str) -> str:
    def repl(m: re.Match[str]) -> str:
        heading = m.group(1)
        inner = re.sub(r"<h2[^>]*>|</h2>", "", heading).strip()
        rest = m.group(2)
        return (
            f'<details class="runners-up" open>\n'
            f"<summary>{inner}</summary>\n"
            f"{rest}\n"
            f"</details>\n"
        )

    return _RUNNERS_UP_SECTION.sub(repl, html)


def _promote_hero_links(html: str) -> str:
    def repl(m: re.Match[str]) -> str:
        url = m.group(1)
        try:
            parsed = urlparse(url)
            host = parsed.hostname or url
            path = parsed.path.rstrip("/")
            label = f"{host}{path}" if path else host
            if len(label) > 60:
                label = label[:57] + "…"
        except Exception:  # pragma: no cover
            label = url
        return f'<p class="hero"><a href="{url}">{label}</a></p>'

    return _HERO_LINK_PARA.sub(repl, html)


def _render_banner(banner_url: str | None) -> str:
    if not banner_url:
        return ""
    src = _resolve_banner_src(banner_url)
    if src is None:
        return ""
    return f'<img class="banner" src="{src}" alt="">'


def _resolve_banner_src(ref: str) -> str | None:
    if re.match(r"^(https?:)?//", ref):
        return ref
    path = Path(ref)
    if not path.is_absolute():
        path = Path.cwd() / path
    if not path.exists():
        log.warning("Banner path does not exist: %s", path)
        return None
    mime, _ = mimetypes.guess_type(str(path))
    mime = mime or "image/png"
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{data}"
